# Generated by Django 5.0.6 on 2024-08-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectovalidacion',
            name='alcance',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('regional', 'Regional'), ('distrital', 'Distrital'), ('provincial', 'Provincial')], default='nacional', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectovalidacion',
            name='aplicado_a',
            field=models.CharField(default='estudiantes', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectovalidacion',
            name='autor_responsable',
            field=models.CharField(default='Desconocido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectovalidacion',
            name='objetivo_general',
            field=models.TextField(default='Objetivo no definido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectovalidacion',
            name='objetivos_especificos',
            field=models.TextField(default='Objetivos no definidos'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('checkbox', 'CheckBox'), ('radiobutton', 'RadioButton'), ('togglebutton', 'ToggleButton'), ('select', 'Select'), ('large_text', 'Large text'), ('short_text', 'Short text'), ('dropbutton', 'DropButton')], max_length=50)),
                ('descripcion', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectovalidacion')),
            ],
        ),
    ]
