# Generated by Django 5.0.6 on 2024-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyectovalidacion_alcance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('estatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='proyectovalidacion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ItemInstrumento',
        ),
        migrations.DeleteModel(
            name='ProyectoValidacion',
        ),
    ]
