# Generated by Django 5.0.6 on 2024-09-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_remove_proyectovalidacion_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('autor_responsable', models.CharField(max_length=255)),
                ('objetivo_general', models.TextField()),
                ('objetivos_especificos', models.TextField()),
                ('alcance', models.CharField(choices=[('Nacional', 'Nacional'), ('Regional', 'Regional'), ('Distrital', 'Distrital'), ('Provincial', 'Provincial')], max_length=50)),
                ('aplicado_a', models.CharField(choices=[('Estudiantes', 'Estudiantes'), ('Docentes', 'Docentes'), ('Directores de centros', 'Directores de centros'), ('Técnicos de educación', 'Técnicos de educación'), ('Otros', 'Otros')], max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Validado', 'Validado')], default='Pendiente', max_length=50)),
                ('items', models.TextField(blank=True, help_text='Lista de ítems seleccionados para el instrumento')),
            ],
        ),
    ]
