# Generated by Django 5.1.1 on 2024-09-30 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_instrumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('autor_responsable', models.CharField(max_length=255)),
                ('objetivo_general', models.TextField()),
                ('objetivos_especificos', models.TextField()),
                ('alcance', models.CharField(choices=[('nacional', 'Nacional'), ('regional', 'Regional'), ('distrital', 'Distrital'), ('provincial', 'Provincial')], max_length=50)),
                ('aplicado_a', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('checkbox', 'CheckBox'), ('radiobutton', 'RadioButton'), ('togglebutton', 'ToggleButton'), ('select', 'Select'), ('large_text', 'Large text'), ('short_text', 'Short text'), ('dropbutton', 'DropButton')], max_length=50)),
                ('descripcion', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectovalidacion')),
            ],
        ),
    ]
