# Generated by Django 5.0.6 on 2024-08-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='affiliation',
            field=models.CharField(default='No especificado', max_length=100, verbose_name='Afiliación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='No especificado', max_length=50, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('evaluador', 'Evaluador'), ('administrador', 'Administrador'), ('usuario', 'Usuario'), ('configuracion', 'Configuración')], max_length=50),
        ),
    ]
