# Generated by Django 5.0.6 on 2024-08-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_affiliation_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('evaluador', 'Evaluador'), ('administrador', 'Administrador'), ('usuario', 'Usuario'), ('configuración', 'Configuración')], max_length=50),
        ),
    ]
