# Generated by Django 5.0.6 on 2024-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('evaluador', 'Evaluador'), ('administrador', 'Administrador'), ('usuario', 'Usuario'), ('configuración', 'Configuración')], default='usuario', max_length=50),
        ),
    ]
